exclude: '^3rd_party/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
        args: [--assume-in-merge]
      - id: check-symlinks # checks for symlinks which do not point to anything.
      - id: destroyed-symlinks # detects symlinks which are changed to regular files.
      - id: detect-private-key # detects the presence of private keys.
      - id: check-toml # checks toml files for parseable syntax.
      - id: check-vcs-permalinks # ensures that links to vcs websites are permalinks.
      - id: debug-statements # checks for debugger imports and breakpoint() calls.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: fix-byte-order-marker # removes utf-8 byte order marker.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: trailing-whitespace # trims trailing whitespace.
      - id: check-json
        exclude: /README\.rst$|\.pot?$
      - id: pretty-format-json
        exclude: /README\.rst$|\.pot?$|\.ipynb$
        args: [--no-sort-keys, --autofix]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa # requires noqa comments to name the silenced rule.
      - id: python-check-blanket-type-ignore # requires type ignores to name the silenced error.

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: [-L, "perturbate,unperturbated,statics,deques,ue,lightening"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.2
    hooks:
      - id: nbstripout

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/efrecon/pre-commit-hook-lxml
    rev: v0.1.4
    hooks:
      - id: format-xml

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.8.3
    hooks:
      - id: pydoclint
        args:
          [
            --style=google,
            --arg-type-hints-in-docstring=false,
            --skip-checking-raises=true,
            --allow-init-docstring=true,
            --check-return-types=false,
            --check-yield-types=false,
          ]
        types: [python]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.21.1"
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
    -   id: add-trailing-comma

  - repo: local
    hooks:
      - id: forbid-merge-leftovers
        name: Forbid merge/rebase leftover files
        entry: git merge/rebase leftover file committed
        language: fail
        files: '\.(orig|rej)$|\.(BACKUP|BASE|LOCAL|REMOTE)\.\d+$'
      - id: basedpyright
        name: basedpyright
        entry: basedpyright --project .
        language: system
        types: [python]
        files: ^src/lead/
        exclude: ^src/lead/expert/
