# Three-camera rig (CARLA_LEADERBOARD2_3CAMERAS).
sensor_rig:
  cameras:
    - pos: [0.1, -0.35, 2.25]
      rot: [0.0, 0.0, -54.5]
      width: 384
      height: 384
      fov: 60
    - pos: [0.35, 0.0, 2.25]
      rot: [0.0, 0.0, 0.0]
      width: 384
      height: 384
      fov: 60
    - pos: [0.1, 0.35, 2.25]
      rot: [0.0, 0.0, 54.5]
      width: 384
      height: 384
      fov: 60
