while true; do
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/PedestrianCrossing" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/noScenarios" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/SignalizedJunctionRightTurn" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/ParkingCrossingPedestrian" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/AccidentTwoWays" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/ParkedObstacleTwoWays" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/DynamicObjectCrossing" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/ParkedObstacle" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/VehicleTurningRoute" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/ConstructionObstacle" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/InvadingTurn" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/SignalizedJunctionLeftTurn" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/SignalizedJunctionLeftTurnEnterFlow" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/OppositeVehicleTakingPriority" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/HighwayExit" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/NonSignalizedJunctionLeftTurn" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/NonSignalizedJunctionLeftTurnEnterFlow" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/OppositeVehicleRunningRedLight" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/EnterActorFlowV2" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/InterurbanAdvancedActorFlow" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/InterurbanActorFlow" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/ParkingExit" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/BlockedIntersection" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/HazardAtSideLaneTwoWays" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/ControlLoss" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/PriorityAtJunction" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/NonSignalizedJunctionRightTurn" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/YieldToEmergencyVehicle" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/HardBreakRoute" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/VehicleTurningRoutePedestrian" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/Accident" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/ConstructionObstacleTwoWays" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/EnterActorFlow" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/ParkingCutIn" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/VehicleOpensDoorTwoWays" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/StaticCutIn" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/HazardAtSideLane" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/HighwayCutIn" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/CrossingBicycleFlow" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/MergerIntoSlowTraffic" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/MergerIntoSlowTrafficV2" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/CrossJunctionDefectTrafficLight" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/RedLightWithoutLeadVehicle" &
    download_dir_tcml "data/carla_leaderboad2_v8/results/data/sensor_data/success_visualization/RedLightWithoutLeadVehicle" &
    wait
done
