while true; do
    while read -r line; do
        rsync -avz --info=progress2 cluster:/mnt/lustre/work/geiger/gwb581/lead/"$line" $line &
    done < <(cat <<EOF | shuf
data/carla_leaderboad2_v6/results/data/sensor_data/zip/PedestrianCrossing
data/carla_leaderboad2_v6/results/data/sensor_data/zip/noScenarios
data/carla_leaderboad2_v6/results/data/sensor_data/zip/SignalizedJunctionRightTurn
data/carla_leaderboad2_v6/results/data/sensor_data/zip/ParkingCrossingPedestrian
data/carla_leaderboad2_v6/results/data/sensor_data/zip/AccidentTwoWays
data/carla_leaderboad2_v6/results/data/sensor_data/zip/ParkedObstacleTwoWays
data/carla_leaderboad2_v6/results/data/sensor_data/zip/DynamicObjectCrossing
data/carla_leaderboad2_v6/results/data/sensor_data/zip/ParkedObstacle
data/carla_leaderboad2_v6/results/data/sensor_data/zip/VehicleTurningRoute
data/carla_leaderboad2_v6/results/data/sensor_data/zip/ConstructionObstacle
data/carla_leaderboad2_v6/results/data/sensor_data/zip/InvadingTurn
data/carla_leaderboad2_v6/results/data/sensor_data/zip/SignalizedJunctionLeftTurn
data/carla_leaderboad2_v6/results/data/sensor_data/zip/OppositeVehicleTakingPriority
data/carla_leaderboad2_v6/results/data/sensor_data/zip/HighwayExit
data/carla_leaderboad2_v6/results/data/sensor_data/zip/NonSignalizedJunctionLeftTurn
data/carla_leaderboad2_v6/results/data/sensor_data/zip/OppositeVehicleRunningRedLight
data/carla_leaderboad2_v6/results/data/sensor_data/zip/EnterActorFlowV2
data/carla_leaderboad2_v6/results/data/sensor_data/zip/InterurbanAdvancedActorFlow
data/carla_leaderboad2_v6/results/data/sensor_data/zip/InterurbanActorFlow
data/carla_leaderboad2_v6/results/data/sensor_data/zip/ParkingExit
data/carla_leaderboad2_v6/results/data/sensor_data/zip/BlockedIntersection
data/carla_leaderboad2_v6/results/data/sensor_data/zip/HazardAtSideLaneTwoWays
data/carla_leaderboad2_v6/results/data/sensor_data/zip/ControlLoss
data/carla_leaderboad2_v6/results/data/sensor_data/zip/PriorityAtJunction
data/carla_leaderboad2_v6/results/data/sensor_data/zip/NonSignalizedJunctionRightTurn
data/carla_leaderboad2_v6/results/data/sensor_data/zip/YieldToEmergencyVehicle
data/carla_leaderboad2_v6/results/data/sensor_data/zip/HardBreakRoute
data/carla_leaderboad2_v6/results/data/sensor_data/zip/VehicleTurningRoutePedestrian
data/carla_leaderboad2_v6/results/data/sensor_data/zip/Accident
data/carla_leaderboad2_v6/results/data/sensor_data/zip/ConstructionObstacleTwoWays
data/carla_leaderboad2_v6/results/data/sensor_data/zip/EnterActorFlow
data/carla_leaderboad2_v6/results/data/sensor_data/zip/ParkingCutIn
data/carla_leaderboad2_v6/results/data/sensor_data/zip/VehicleOpensDoorTwoWays
data/carla_leaderboad2_v6/results/data/sensor_data/zip/StaticCutIn
data/carla_leaderboad2_v6/results/data/sensor_data/zip/HazardAtSideLane
data/carla_leaderboad2_v6/results/data/sensor_data/zip/HighwayCutIn
data/carla_leaderboad2_v6/results/data/sensor_data/zip/CrossingBicycleFlow
data/carla_leaderboad2_v6/results/data/sensor_data/zip/MergerIntoSlowTraffic
data/carla_leaderboad2_v6/results/data/sensor_data/zip/MergerIntoSlowTrafficV2
data/carla_leaderboad2_v6/results/data/sensor_data/zip/T_Junction
data/carla_leaderboad2_v6/results/data/sensor_data/zip/RedLightWithoutLeadVehicle
EOF
    )
    wait
done
